<?php

/**
 * @file
 * Contains rmp_reports.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rmp_reports_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rmp_reports module.
    case 'help.page.rmp_reports':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RMP reports') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rmp_reports_theme() {
  $theme = [];
  $theme['practice_view_report'] = array(
    'render element' => 'form',
    'template' => 'practice-view-report',
  );

  return $theme;
}
