<?php

/**
 * @file
 * Contains rmp_resource_import.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rmp_resource_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rmp_resource_import module.
    case 'help.page.rmp_resource_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import resources from XLS sheet') . '</p>';
      return $output;

    default:
  }
}
