<?php

/**
 * @file
 * Contains facebook_posts.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function facebook_posts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the facebook_posts module.
    case 'help.page.facebook_posts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is intended to fetch the facebook posts, images and likes for the post.') . '</p>';
      return $output;

    default:
  }
}
